#!/bin/bash -e

mysql --password="$MYSQL_ROOT_PASSWORD" -h $MYSQL_HOST <<MYSQL_SCRIPT
CREATE DATABASE IF NOT EXISTS $USER;
CREATE USER IF NOT EXISTS '$USER'@'%' IDENTIFIED BY '$PASSWORD';
GRANT ALL PRIVILEGES ON $USER.* TO '$USER'@'%';
FLUSH PRIVILEGES;
MYSQL_SCRIPT

echo "MySQL user $USER created."